version: "3.2"
services:
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password

  unit-test:
    build:
      context: .
    depends_on:
      - pg
    environment:
      PGHOST: pg
      PGPASSWORD: password
      PGUSER: postgres
    volumes:
      - /usr/src/app/node_modules
